#!/usr/bin/env node
// End-to-end test for association sets: publish a set, deposit, withdraw on a
// proof that shows membership of both the pool and the set, and check that a
// set the deposit is NOT in cannot be used.
//
// The proving key here is a throwaway generated by the repository, not the one
// the public ceremony is producing. It proves the circuit, the program and the
// client agree; it proves nothing about the ceremony.
//
//   node scripts/e2e-set.mjs
import {
  Connection,
  Keypair,
  PublicKey,
  SystemProgram,
  Transaction,
  TransactionInstruction,
  ComputeBudgetProgram,
  sendAndConfirmTransaction,
  LAMPORTS_PER_SOL,
} from "@solana/web3.js";
import { groth16 } from "../circuits/node_modules/snarkjs/build/main.cjs";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { newReceipt, buildTree, splitPubkey, bytes32 } from "../client/pool.mjs";

const args = Object.fromEntries(
  process.argv.slice(2).flatMap((a, i, all) => (a.startsWith("--") ? [[a.slice(2), all[i + 1] ?? true]] : [])),
);
const RPC_URL = args.url || "http://127.0.0.1:8899";
const PROGRAM_ID = new PublicKey(
  readFileSync(new URL("../Anchor.toml", import.meta.url), "utf8").match(/keephost_pool = "([^"]+)"/)[1],
);
const DENOM = BigInt(args.denom || 100_000_000);

const FILES = {
  wasm: new URL("../circuits/assoc-build/withdraw-assoc_js/withdraw-assoc.wasm", import.meta.url).pathname,
  zkey: new URL("../circuits/assoc-build/assoc_test.zkey", import.meta.url).pathname,
};

const conn = new Connection(RPC_URL, "confirmed");
const payer = args.keypair
  ? Keypair.fromSecretKey(Uint8Array.from(JSON.parse(readFileSync(args.keypair, "utf8"))))
  : Keypair.generate();

const disc = (name) => createHash("sha256").update(`global:${name}`).digest().subarray(0, 8);
const u64 = (v) => {
  const b = Buffer.alloc(8);
  b.writeBigUInt64LE(BigInt(v));
  return b;
};
const log = (...a) => console.log(...a);

const poolPda = PublicKey.findProgramAddressSync(
  [Buffer.from("pool"), payer.publicKey.toBuffer(), u64(DENOM)],
  PROGRAM_ID,
)[0];
const vaultPda = PublicKey.findProgramAddressSync([Buffer.from("vault"), poolPda.toBuffer()], PROGRAM_ID)[0];
const feesPda = PublicKey.findProgramAddressSync([Buffer.from("fees"), poolPda.toBuffer()], PROGRAM_ID)[0];

async function fund(sol) {
  if ((await conn.getBalance(payer.publicKey)) >= sol * LAMPORTS_PER_SOL) return;
  const sig = await conn.requestAirdrop(payer.publicKey, sol * LAMPORTS_PER_SOL);
  await conn.confirmTransaction(sig, "confirmed");
}

async function send(ix, extra = []) {
  const tx = new Transaction().add(ComputeBudgetProgram.setComputeUnitLimit({ units: 900_000 }), ix);
  return sendAndConfirmTransaction(conn, tx, [payer, ...extra], { commitment: "confirmed" });
}

async function openPool() {
  if (await conn.getAccountInfo(poolPda)) return;
  await send(
    new TransactionInstruction({
      programId: PROGRAM_ID,
      keys: [
        { pubkey: payer.publicKey, isSigner: true, isWritable: true },
        { pubkey: poolPda, isSigner: false, isWritable: true },
        { pubkey: vaultPda, isSigner: false, isWritable: true },
        { pubkey: SystemProgram.programId, isSigner: false, isWritable: false },
      ],
      data: Buffer.concat([disc("initialize"), u64(DENOM), Buffer.from([0])]),
    }),
  );
  log("pool open:", poolPda.toBase58());
}

async function deposit(receipt) {
  return send(
    new TransactionInstruction({
      programId: PROGRAM_ID,
      keys: [
        { pubkey: payer.publicKey, isSigner: true, isWritable: true },
        { pubkey: poolPda, isSigner: false, isWritable: true },
        { pubkey: vaultPda, isSigner: false, isWritable: true },
        { pubkey: feesPda, isSigner: false, isWritable: true },
        { pubkey: PROGRAM_ID, isSigner: false, isWritable: false },
        { pubkey: SystemProgram.programId, isSigner: false, isWritable: false },
      ],
      data: Buffer.concat([disc("deposit"), Buffer.from(bytes32(receipt.commitment))]),
    }),
  );
}

async function publishSet(root, label) {
  const rootBytes = Buffer.from(bytes32(root));
  const [setPda] = PublicKey.findProgramAddressSync(
    [Buffer.from("assoc"), payer.publicKey.toBuffer(), rootBytes],
    PROGRAM_ID,
  );
  if (!(await conn.getAccountInfo(setPda))) {
    const labelBytes = Buffer.alloc(32);
    labelBytes.write(label);
    await send(
      new TransactionInstruction({
        programId: PROGRAM_ID,
        keys: [
          { pubkey: payer.publicKey, isSigner: true, isWritable: true },
          { pubkey: setPda, isSigner: false, isWritable: true },
          { pubkey: SystemProgram.programId, isSigner: false, isWritable: false },
        ],
        data: Buffer.concat([disc("publish_set"), rootBytes, labelBytes]),
      }),
    );
  }
  return setPda;
}

async function prove({ receipt, leaves, index, setLeaves, setIndex, recipient, fee }) {
  const tree = await buildTree(leaves);
  const path = tree.path(index);
  const setTree = await buildTree(setLeaves);
  const setPath = setTree.path(setIndex);

  const r = splitPubkey(recipient.toBytes());
  const l = splitPubkey(payer.publicKey.toBytes());
  const p = splitPubkey(poolPda.toBytes());

  const { proof } = await groth16.fullProve(
    {
      root: tree.root.toString(),
      nullifierHash: receipt.nullifierHash.toString(),
      recipientHi: r.hi.toString(),
      recipientLo: r.lo.toString(),
      relayerHi: l.hi.toString(),
      relayerLo: l.lo.toString(),
      fee: String(fee),
      poolHi: p.hi.toString(),
      poolLo: p.lo.toString(),
      assocRoot: setTree.root.toString(),
      nullifier: receipt.nullifier.toString(),
      secret: receipt.secret.toString(),
      pathElements: path.elements.map((e) => e.toString()),
      pathIndices: path.indices.map((i) => i.toString()),
      assocPathElements: setPath.elements.map((e) => e.toString()),
      assocPathIndices: setPath.indices.map((i) => i.toString()),
    },
    FILES.wasm,
    FILES.zkey,
  );

  const BASE = 21888242871839275222246405745257275088696311157297823662689037894645226208583n;
  const negY = (y) => (BASE - (BigInt(y) % BASE)) % BASE;
  const cat = (...a) => Buffer.concat(a.map((x) => Buffer.from(x)));
  return {
    root: tree.root,
    assocRoot: setTree.root,
    a: cat(bytes32(BigInt(proof.pi_a[0])), bytes32(negY(proof.pi_a[1]))),
    b: cat(
      bytes32(BigInt(proof.pi_b[0][1])),
      bytes32(BigInt(proof.pi_b[0][0])),
      bytes32(BigInt(proof.pi_b[1][1])),
      bytes32(BigInt(proof.pi_b[1][0])),
    ),
    c: cat(bytes32(BigInt(proof.pi_c[0])), bytes32(BigInt(proof.pi_c[1]))),
  };
}

function withdrawIx({ setPda, recipient, proof, receipt, fee }) {
  const [nullifierPda] = PublicKey.findProgramAddressSync(
    [Buffer.from("nullifier"), poolPda.toBuffer(), Buffer.from(bytes32(receipt.nullifierHash))],
    PROGRAM_ID,
  );
  return new TransactionInstruction({
    programId: PROGRAM_ID,
    keys: [
      { pubkey: payer.publicKey, isSigner: true, isWritable: true },
      { pubkey: poolPda, isSigner: false, isWritable: false },
      { pubkey: vaultPda, isSigner: false, isWritable: true },
      { pubkey: recipient, isSigner: false, isWritable: true },
      { pubkey: setPda, isSigner: false, isWritable: false },
      { pubkey: nullifierPda, isSigner: false, isWritable: true },
      { pubkey: SystemProgram.programId, isSigner: false, isWritable: false },
    ],
    data: Buffer.concat([
      disc("withdraw_with_set"),
      proof.a,
      proof.b,
      proof.c,
      Buffer.from(bytes32(proof.root)),
      Buffer.from(bytes32(receipt.nullifierHash)),
      u64(fee),
    ]),
  });
}

async function main() {
  log("network:", RPC_URL);
  await fund(3);
  await openPool();

  const receipts = [await newReceipt(), await newReceipt(), await newReceipt()];
  for (const r of receipts) await deposit(r);
  const leaves = receipts.map((r) => r.commitment);
  log(`${leaves.length} deposits in the pool`);

  // A set that holds two of the three deposits — ours among them — and a set
  // that deliberately leaves ours out.
  const inSet = [leaves[0], leaves[1]];
  const outSet = [leaves[0], leaves[2]];
  const inTree = await buildTree(inSet);
  const outTree = await buildTree(outSet);
  const inPda = await publishSet(inTree.root, "includes ours");
  const outPda = await publishSet(outTree.root, "excludes ours");
  log("two sets published");

  const recipient = Keypair.generate().publicKey;
  const before = await conn.getBalance(recipient);
  const fee = 0;
  const proof = await prove({
    receipt: receipts[1],
    leaves,
    index: 1,
    setLeaves: inSet,
    setIndex: 1,
    recipient,
    fee,
  });
  const sig = await send(withdrawIx({ setPda: inPda, recipient, proof, receipt: receipts[1], fee }));
  const got = (await conn.getBalance(recipient)) - before;
  log(`withdrawal proving membership of the set · ${sig.slice(0, 20)}…`);
  log(`received ${got / LAMPORTS_PER_SOL} SOL`);
  if (BigInt(got) !== DENOM - BigInt(fee)) throw new Error("unexpected amount received");

  // The same proof against a set that does not contain this deposit: the root
  // in the proof no longer matches the set account, so the program refuses it.
  let wrongSet = "refused";
  try {
    await send(withdrawIx({ setPda: outPda, recipient, proof, receipt: receipts[2], fee }));
    wrongSet = "ACCEPTED — FLAW";
  } catch {}
  log("withdrawal claiming a set it is not in:", wrongSet);
  if (wrongSet !== "refused") process.exit(1);

  log("");
  log("OK — a withdrawal proves membership of the pool and of a chosen set, and only of a set it is really in.");
}

main().catch((e) => {
  console.error("failed:", e.message);
  if (e.logs) console.error(e.logs.slice(-5).join("\n"));
  process.exit(1);
});
