#!/usr/bin/env node
// Converts the association-set verification key to
// programs/keephost-pool/src/verifying_key_assoc.rs.
//
// Separate from vkey.mjs on purpose: the two keys live side by side in the
// program, so a receipt written before association sets keeps working while a
// new one proves membership of a set. One key replacing the other would have
// meant a day where nobody could withdraw.
//
//   node scripts/vkey-assoc.mjs
import { readFileSync, writeFileSync } from "node:fs";

const vk = JSON.parse(readFileSync(new URL("../circuits/assoc-build/verification_key_assoc.json", import.meta.url), "utf8"));
if (vk.protocol !== "groth16" || vk.curve !== "bn128") throw new Error("unexpected key: " + vk.protocol + "/" + vk.curve);

const be = (dec) => BigInt(dec).toString(16).padStart(64, "0");
const g1 = (p) => be(p[0]) + be(p[1]);
// G2 components are swapped relative to the snarkjs JSON: the alt_bn128
// syscalls read x.c1‖x.c0‖y.c1‖y.c0.
const g2 = (p) => be(p[0][1]) + be(p[0][0]) + be(p[1][1]) + be(p[1][0]);

const rust = (hex, indent = "    ") => {
  const bytes = hex.match(/../g).map((b) => "0x" + b);
  const lines = [];
  for (let i = 0; i < bytes.length; i += 8) lines.push(indent + "    " + bytes.slice(i, i + 8).join(", ") + ",");
  return "[\n" + lines.join("\n") + "\n" + indent + "]";
};

const ic = vk.IC.map((p) => "        " + rust(g1(p), "        ") + ",").join("\n");

const out = `//! Verification key — generated by scripts/vkey.mjs, do not edit by hand.
//!
//! Changing the circuit or redoing the ceremony requires regenerating this file
//! AND redeploying: a key that does not match the circuit makes every proof fail.

use groth16_solana::groth16::Groth16Verifyingkey;

pub const VERIFYINGKEY_ASSOC: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: ${vk.nPublic},

    vk_alpha_g1: ${rust(g1(vk.vk_alpha_1))},

    vk_beta_g2: ${rust(g2(vk.vk_beta_2))},

    vk_gamme_g2: ${rust(g2(vk.vk_gamma_2))},

    vk_delta_g2: ${rust(g2(vk.vk_delta_2))},

    vk_ic: &[
${ic}
    ],
};
`;

writeFileSync(new URL("../programs/keephost-pool/src/verifying_key_assoc.rs", import.meta.url), out);
console.log(`verification key written · ${vk.nPublic} public inputs · ${vk.IC.length} IC points`);
