#!/usr/bin/env node
// Generates the empty-tree constants (programs/keephost-pool/src/zeros.rs and
// client/zeros.json).
//
//   node scripts/zeros.mjs
import { buildPoseidon } from "../circuits/node_modules/circomlibjs/src/poseidon_wasm.js";
import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";

const P = 21888242871839275222246405745257275088548364400416034343698204186575808495617n;
const LEVELS = 20;

// The empty leaf is derived from a phrase so that no Poseidon preimage is
// known for it: it can never be mistaken for a real commitment.
const seed = BigInt("0x" + createHash("sha256").update("KeepHost pool v1").digest("hex")) % P;

const poseidon = await buildPoseidon();
const F = poseidon.F;
const toHex = (v) => F.toObject(v).toString(16).padStart(64, "0");

const zeros = [seed.toString(16).padStart(64, "0")];
for (let i = 0; i < LEVELS; i++) {
  const prev = BigInt("0x" + zeros[i]);
  zeros.push(toHex(poseidon([prev, prev])));
}

const rustRows = zeros
  .map((h, i) => {
    const bytes = h.match(/../g).map((b) => "0x" + b);
    const lines = [];
    for (let k = 0; k < 32; k += 8) lines.push("        " + bytes.slice(k, k + 8).join(", ") + ",");
    return `    // level ${i}\n    [\n${lines.join("\n")}\n    ],`;
  })
  .join("\n");

writeFileSync(
  new URL("../programs/keephost-pool/src/zeros.rs", import.meta.url),
  `//! Empty tree — generated by scripts/zeros.mjs, do not edit by hand.
//!
//! ZEROS[0] is the empty leaf, ZEROS[i+1] = Poseidon(ZEROS[i], ZEROS[i]).
//! ZEROS[20] is the root of an empty pool, the first root written by \`initialize\`.

pub const ZEROS: [[u8; 32]; ${LEVELS + 1}] = [
${rustRows}
];
`,
);

writeFileSync(new URL("../client/zeros.json", import.meta.url), JSON.stringify({ levels: LEVELS, zeros }, null, 1) + "\n");
console.log("empty leaf:", zeros[0]);
console.log("root of an empty pool:", zeros[LEVELS]);
